const appData = [
  {
    id: '1',
    fName: 'John',
    sName: 'Doe',
    eMail: 'john.doe@email.com',
    phNumber: '0732894832',
    position: ' ',
    city: 'Bucharest',
    state: 'Romania',
    comments: ' ',
  },
  {
    id: '2',
    fName: 'John',
    sName: 'Doe',
    eMail: 'john.doe@email.com',
    phNumber: '0732894832',
    position: ' ',
    city: 'Bucharest',
    state: 'Romania',
    comments: ' ',
  },
  {
    id: '3',
    fName: 'John',
    sName: 'Doe',
    eMail: 'john.doe@email.com',
    phNumber: '0732894832',
    position: ' ',
    city: 'Bucharest',
    state: 'Romania',
    comments: ' ',
  },
  {
    id: '4',
    fName: 'John',
    sName: 'Doe',
    eMail: 'john.doe@email.com',
    phNumber: '0732894832',
    position: ' ',
    city: 'Bucharest',
    state: 'Romania',
    comments: ' ',
  },
  {
    id: '5',
    fName: 'John',
    sName: 'Doe',
    eMail: 'john.doe@email.com',
    phNumber: '0732894832',
    position: ' ',
    city: 'Bucharest',
    state: 'Romania',
    comments: ' ',
  },
];

export default appData;
